[package]
name = "nextcloud-config-parser"
description = "Rust parser for nextcloud config files"
version = "0.8.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icewind1991/nextcloud-config-parser"
documentation = "https://docs.rs/nextcloud-config-parser"
rust-version = "1.58"

[dependencies]
redis = { version = "0.23.0", optional = true, default-features = false }
thiserror = "1.0.40"
php-literal-parser = "0.5.1"
sqlx = { version = "0.6.3", default-features = false, features = ["runtime-tokio-rustls", "any", "mysql", "sqlite", "postgres"], optional = true }
miette = "5.8.0"

[dev-dependencies]
sqlx = { version = "0.6.3", default-features = false, features = ["runtime-tokio-rustls", "any", "mysql", "sqlite", "postgres"] }
miette = { version = "5.8.0", features = ["fancy"] }

[features]
db-sqlx = ["sqlx"]
redis-connect = ["redis"]
